/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef EXAMPLE_TEXT_GEN_CLASS_H
#define EXAMPLE_TEXT_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class example_text_gen_class
{
 protected:
  string generator;
  string name;
  string progname;
  string version;

 public:
  example_text_gen_class()
  {
  }
  
  example_text_gen_class(const string &_generator, const string &_name, const string &_progname, const string &_version) :
    generator (_generator), name (_name), progname (_progname), version (_version)
  {
  }

  void set_generator(const string &_generator)
  {
    generator = _generator;
  }

  void set_name(const string &_name)
  {
    name = _name;
  }

  void set_progname(const string &_progname)
  {
    progname = _progname;
  }

  void set_version(const string &_version)
  {
    version = _version;
  }

  void generate_example_text(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "This is ";
    stream << name;
    stream << " generated by the program ";
    stream << progname;
    stream << ".";
    stream << "\n";
    stream << indent_str;
    stream << "The code of ";
    stream << progname;
    stream << " that generated this text was";
    stream << "\n";
    stream << indent_str;
    stream << "generated by ";
    stream << generator;
    stream << " version ";
    stream << version;
    stream << ", made by";
    stream << "\n";
    stream << indent_str;
    stream << "Lorenzo Bettini <foobar";
    stream << "@";
    stream << "foo.org>.";
  }
};

#endif // EXAMPLE_TEXT_GEN_CLASS_H
