/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TEST_CICLE_GEN_STRUCT_H
#define TEST_CICLE_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct test_cicle_gen_struct
{
  const char *loop;
  const char *loopnum;
  short printnumloop;
  short printsomething;
  const char *return_st;
  short zeroloops;
};

extern void generate_loop(FILE *stream, struct test_cicle_gen_struct *record, unsigned int indent);


extern void generate_return_st(FILE *stream, struct test_cicle_gen_struct *record, unsigned int indent);


void
generate_test_cicle(FILE *stream, struct test_cicle_gen_struct *record, unsigned int indent);

void
generatep_test_cicle(FILE *stream, unsigned int indent, const char *loop, const char *loopnum, short printnumloop, short printsomething, const char *return_st, short zeroloops);

char *
genstring_test_cicle(struct test_cicle_gen_struct *record, unsigned int indent);

char *
genstringp_test_cicle(unsigned int indent, const char *loop, const char *loopnum, short printnumloop, short printsomething, const char *return_st, short zeroloops);

int
strcnt_test_cicle(struct test_cicle_gen_struct *record, unsigned int indent);

void
init_test_cicle_gen_struct(struct test_cicle_gen_struct *record);


static void
generate_string(const char *s, FILE *stream, unsigned int indent)
{
  const char *sub = s;
  char *indent_str;
  unsigned int i;

  if (!indent || strchr (s, '\n') == 0)
    {
      fprintf (stream, "%s", s);
      return;
    }

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  while ( (sub=strchr (s, '\n')) != 0 )
    {
      fwrite (s, sizeof(char), (sub-s)+1, stream);
      s = sub+1;
      if (s[0])
        fprintf (stream, "%s", indent_str);
    }
  if (s[0])
    fwrite (s, sizeof(char), strlen (s), stream);

  free (indent_str);
}

void
generate_test_cicle(FILE *stream, struct test_cicle_gen_struct *record, unsigned int indent)
{
  char *indent_str;
  unsigned int i;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';
  indent = 0;

  fprintf (stream, "%s", "#include <iostream>");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "using std::cout;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "using std::endl;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#define NUM_OF_LOOPS ");
  fprintf (stream, "%s", (record->loopnum ? record->loopnum : ""));
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "int");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "main()");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "{");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "  cout << \"The val of NUM_OF_LOOPS is \";");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "  cout << ");
  fprintf (stream, "%s", (record->loopnum ? record->loopnum : ""));
  fprintf (stream, "%s", " << endl;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  if (record->zeroloops)
    {
      fprintf (stream, "%s", "  /*");
      fprintf (stream, "%s", "\n");
      fprintf (stream, "%s", indent_str);
      fprintf (stream, "%s", "   * No loop generated since NUM_OF_LOOPS is 0");
      fprintf (stream, "%s", "\n");
      fprintf (stream, "%s", indent_str);
      fprintf (stream, "%s", "   */");
      fprintf (stream, "%s", "\n");
      fprintf (stream, "%s", indent_str);
    }
  else
    {
      if (record->printsomething)
        {
          if (record->printnumloop)
            {
              fprintf (stream, "%s", "  cout << \"zero loops: \" << ");
              fprintf (stream, "%s", (record->loopnum ? record->loopnum : ""));
              fprintf (stream, "%s", " << endl;");
              fprintf (stream, "%s", "\n");
              fprintf (stream, "%s", indent_str);
            }
          else
            {
              fprintf (stream, "%s", "  cout << \"zero loops!\" << endl;");
              fprintf (stream, "%s", "\n");
              fprintf (stream, "%s", indent_str);
            }
        }
      else
        {
          indent = 2;
          fprintf (stream, "%s", "  ");
          if (record->loop)
            generate_string (record->loop, stream, indent + strlen (indent_str));
          else
            generate_loop (stream, record, indent + strlen (indent_str));
          indent = 0;
          fprintf (stream, "%s", "\n");
          fprintf (stream, "%s", indent_str);
          if (record->zeroloops)
            {
              
          
            }
          else
            {
              
          
            }
          if (record->zeroloops)
            {
              
          
            }
          else
            {
              
          
            }
          if (record->zeroloops)
            {
              
          
            }
        }
    }
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  indent = 2;
  fprintf (stream, "%s", "  ");
  if (record->return_st)
    generate_string (record->return_st, stream, indent + strlen (indent_str));
  else
    generate_return_st (stream, record, indent + strlen (indent_str));
  indent = 0;
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "}");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);

  free (indent_str);
}

void
generatep_test_cicle(FILE *stream, unsigned int indent, const char *loop, const char *loopnum, short printnumloop, short printsomething, const char *return_st, short zeroloops)
{
  struct test_cicle_gen_struct record;
  
  record.loop = loop;
  record.loopnum = loopnum;
  record.printnumloop = printnumloop;
  record.printsomething = printsomething;
  record.return_st = return_st;
  record.zeroloops = zeroloops;

  generate_test_cicle (stream, &record, indent);
}

char *
genstring_test_cicle(struct test_cicle_gen_struct *record, unsigned int indent)
{
  char *indent_str, *output;
  unsigned int i;
  int len;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  len = strcnt_test_cicle (record, indent);
  output = (char *) malloc (len + 1);
  output[0] = '\0';

  strcat (output, "#include <iostream>");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "using std::cout;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "using std::endl;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#define NUM_OF_LOOPS ");
  if (record->loopnum) strcat (output, record->loopnum);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "int");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "main()");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "{");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "  cout << \"The val of NUM_OF_LOOPS is \";");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "  cout << ");
  if (record->loopnum) strcat (output, record->loopnum);
  strcat (output, " << endl;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  if (record->zeroloops)
    {
      strcat (output, "  /*");
      strcat (output, "\n");
      strcat (output, indent_str);
      strcat (output, "   * No loop generated since NUM_OF_LOOPS is 0");
      strcat (output, "\n");
      strcat (output, indent_str);
      strcat (output, "   */");
      strcat (output, "\n");
      strcat (output, indent_str);
    }
  else
    {
      if (record->printsomething)
        {
          if (record->printnumloop)
            {
              strcat (output, "  cout << \"zero loops: \" << ");
              if (record->loopnum) strcat (output, record->loopnum);
              strcat (output, " << endl;");
              strcat (output, "\n");
              strcat (output, indent_str);
            }
          else
            {
              strcat (output, "  cout << \"zero loops!\" << endl;");
              strcat (output, "\n");
              strcat (output, indent_str);
            }
        }
      else
        {
          strcat (output, "  ");
          if (record->loop) strcat (output, record->loop);
          strcat (output, "\n");
          strcat (output, indent_str);
          if (record->zeroloops)
            {
              
          
            }
          else
            {
              
          
            }
          if (record->zeroloops)
            {
              
          
            }
          else
            {
              
          
            }
          if (record->zeroloops)
            {
              
          
            }
        }
    }
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "  ");
  if (record->return_st) strcat (output, record->return_st);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "}");
  strcat (output, "\n");
  strcat (output, indent_str);

  free (indent_str);

  return output;
}

char *
genstringp_test_cicle(unsigned int indent, const char *loop, const char *loopnum, short printnumloop, short printsomething, const char *return_st, short zeroloops)
{
  struct test_cicle_gen_struct record;
  
  record.loop = loop;
  record.loopnum = loopnum;
  record.printnumloop = printnumloop;
  record.printsomething = printsomething;
  record.return_st = return_st;
  record.zeroloops = zeroloops;

  return genstring_test_cicle (&record, indent);
}

int
strcnt_test_cicle(struct test_cicle_gen_struct *record, unsigned int indent)
{
  int length = 0;
  
  length += (record->loopnum ? strlen (record->loopnum) : 0) * 3;
if (record->zeroloops)
    {
      

    }
  else
    {
      if (record->printsomething)
        {
          if (record->printnumloop)
            {
              
          
            }
          else
            {
              
          
            }
        }
      else
        {
          length += (record->loop ? strlen (record->loop) : 0) * 1;
          if (record->zeroloops)
            {
              
          
            }
          else
            {
              
          
            }
          if (record->zeroloops)
            {
              
          
            }
          else
            {
              
          
            }
          if (record->zeroloops)
            {
              
          
            }
        }
    }
  length += (record->return_st ? strlen (record->return_st) : 0) * 1;

  return length + 324;
}

void
init_test_cicle_gen_struct(struct test_cicle_gen_struct *record)
{
  record->loop = 0;
  record->loopnum = 0;
  record->printnumloop = 0;
  record->printsomething = 0;
  record->return_st = 0;
  record->zeroloops = 0;
}

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // TEST_CICLE_GEN_STRUCT_H
