/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TEST1_GEN_CLASS_H
#define TEST1_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class test1_gen_class
{
 protected:
  string i;

 public:
  test1_gen_class()
  {
  }
  
  test1_gen_class(const string &_i) :
    i (_i)
  {
  }

  void set_i(const string &_i)
  {
    i = _i;
  }

  void generate_test1(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "if (";
    stream << i;
    stream << " < 10)";
    stream << "\n";
    stream << indent_str;
    stream << "  printf(\"the value of ";
    stream << i;
    stream << " is %d\", ";
    stream << i;
    stream << ");";
  }
};

#endif // TEST1_GEN_CLASS_H
