/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TEST_ITER_GEN_CLASS_H
#define TEST_ITER_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class test_iter_gen_class
{
 protected:
  string loop;
  string test;

 public:
  test_iter_gen_class()
  {
  }
  
  test_iter_gen_class(const string &_loop, const string &_test) :
    loop (_loop), test (_test)
  {
  }

  virtual ~test_iter_gen_class()
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  virtual void generate_loop(ostream &stream, unsigned int indent) = 0;

  void set_loop(const string &_loop)
  {
    loop = _loop;
  }

  void set_test(const string &_test)
  {
    test = _test;
  }

  void generate_test_iter(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "#include <iostream>";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "using std::cout;";
    stream << "\n";
    stream << indent_str;
    stream << "using std::endl;";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "int";
    stream << "\n";
    stream << indent_str;
    stream << "main()";
    stream << "\n";
    stream << indent_str;
    stream << "{";
    stream << "\n";
    stream << indent_str;
    stream << "  if (";
    stream << test;
    stream << ")";
    stream << "\n";
    stream << indent_str;
    stream << "    {";
    stream << "\n";
    stream << indent_str;
    indent = 6;
    if (loop.size () > 0)
      generate_string (loop, stream, indent + indent_str.length ());
    else
      generate_loop (stream, indent + indent_str.length ());
    indent = 0;
    stream << indent_str;
    stream << "    }";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "  if (";
    stream << test;
    stream << ")";
    stream << "\n";
    stream << indent_str;
    stream << "    {";
    stream << "\n";
    stream << indent_str;
    indent = 6;
    if (loop.size () > 0)
      generate_string (loop, stream, indent + indent_str.length ());
    else
      generate_loop (stream, indent + indent_str.length ());
    indent = 0;
    stream << indent_str;
    stream << "    }";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "  return 0;";
    stream << "\n";
    stream << indent_str;
    stream << "}";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // TEST_ITER_GEN_CLASS_H
