/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TEST_CICLE_GEN_STRUCT_H
#define TEST_CICLE_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct test_cicle_gen_struct
{
  const char *loop;
  const char *loopnum;
  short printnumloop;
  short printsomething;
  const char *return_st;
  short zeroloops;
};

extern void generate_loop(FILE *stream, struct test_cicle_gen_struct *record, unsigned int indent);


extern void generate_return_st(FILE *stream, struct test_cicle_gen_struct *record, unsigned int indent);


void
generate_test_cicle(FILE *stream, struct test_cicle_gen_struct *record, unsigned int indent);

void
generatep_test_cicle(FILE *stream, unsigned int indent, const char *loop, const char *loopnum, short printnumloop, short printsomething, const char *return_st, short zeroloops);

char *
genstring_test_cicle(struct test_cicle_gen_struct *record, unsigned int indent);

char *
genstringp_test_cicle(unsigned int indent, const char *loop, const char *loopnum, short printnumloop, short printsomething, const char *return_st, short zeroloops);

int
strcnt_test_cicle(struct test_cicle_gen_struct *record, unsigned int indent);

void
init_test_cicle_gen_struct(struct test_cicle_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // TEST_CICLE_GEN_STRUCT_H
