/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TEST_BODY_LOOP_GEN_CLASS_H
#define TEST_BODY_LOOP_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class test_body_loop_gen_class
{
 protected:
  string end;
  string start;

 public:
  test_body_loop_gen_class()
  {
  }
  
  test_body_loop_gen_class(const string &_end, const string &_start) :
    end (_end), start (_start)
  {
  }

  void set_end(const string &_end)
  {
    end = _end;
  }

  void set_start(const string &_start)
  {
    start = _start;
  }

  void generate_test_body_loop(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "cout << \"These are the numbers from \" << ";
    stream << "\n";
    stream << indent_str;
    indent = 8;
    stream << "        ";
    stream << start;
    stream << " << \" to \" << ";
    stream << end;
    stream << " << endl;";
    indent = 0;
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "for (int i = ";
    stream << start;
    stream << "; i <= ";
    stream << end;
    stream << "; ++i)";
    stream << "\n";
    stream << indent_str;
    stream << "   cout << i << \" \";";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "cout << endl;";
  }
};

#endif // TEST_BODY_LOOP_GEN_CLASS_H
