/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TEST_SUBST_GEN_CLASS_H
#define TEST_SUBST_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class test_subst_gen_class
{
 protected:

 public:
  test_subst_gen_class()
  {
  }
  

  void generate_test_subst(ostream &stream, unsigned int indent = 0);
  
};

#endif // TEST_SUBST_GEN_CLASS_H
