/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TEST_CICLE_GEN_CLASS_H
#define TEST_CICLE_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class test_cicle_gen_class
{
 protected:
  string loop;
  string loopnum;
  string return_st;

 public:
  test_cicle_gen_class()
  {
  }
  
  test_cicle_gen_class(const string &_loop, const string &_loopnum, const string &_return_st) :
    loop (_loop), loopnum (_loopnum), return_st (_return_st)
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  void set_loop(const string &_loop)
  {
    loop = _loop;
  }

  void set_loopnum(const string &_loopnum)
  {
    loopnum = _loopnum;
  }

  void set_return_st(const string &_return_st)
  {
    return_st = _return_st;
  }

  void generate_test_cicle(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "#include <iostream>";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "using std::cout;";
    stream << "\n";
    stream << indent_str;
    stream << "using std::endl;";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "#define NUM_OF_LOOPS ";
    generate_string (loopnum, stream, indent + indent_str.length ());
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "int";
    stream << "\n";
    stream << indent_str;
    stream << "main()";
    stream << "\n";
    stream << indent_str;
    stream << "{";
    stream << "\n";
    stream << indent_str;
    stream << "  cout << \"The val of NUM_OF_LOOPS is \";";
    stream << "\n";
    stream << indent_str;
    stream << "  cout << ";
    generate_string (loopnum, stream, indent + indent_str.length ());
    stream << " << endl;";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    indent = 2;
    stream << "  ";
    generate_string (loop, stream, indent + indent_str.length ());
    indent = 0;
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    indent = 2;
    stream << "  ";
    generate_string (return_st, stream, indent + indent_str.length ());
    indent = 0;
    stream << "\n";
    stream << indent_str;
    stream << "}";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // TEST_CICLE_GEN_CLASS_H
