/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TEST_VARS_GEN_CLASS_H
#define TEST_VARS_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class test_vars_gen_class
{
 protected:
  string mydef;
  string myvar;

 public:
  test_vars_gen_class()
  {
  }
  
  test_vars_gen_class(const string &_mydef, const string &_myvar) :
    mydef (_mydef), myvar (_myvar)
  {
  }

  void set_mydef(const string &_mydef)
  {
    mydef = _mydef;
  }

  void set_myvar(const string &_myvar)
  {
    myvar = _myvar;
  }

  void generate_test_vars(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "/*";
    stream << "\n";
    stream << indent_str;
    stream << " * Copyright (C) 2002  Lorenzo Bettini  <http://www.lorenzobettini.it>";
    stream << "\n";
    stream << indent_str;
    stream << " *";
    stream << "\n";
    stream << indent_str;
    stream << " * This program is free software; you can redistribute it and/or modify";
    stream << "\n";
    stream << indent_str;
    stream << " * it under the terms of the GNU General Public License as published by";
    stream << "\n";
    stream << indent_str;
    stream << " * the Free Software Foundation; either version 2 of the License, or";
    stream << "\n";
    stream << indent_str;
    stream << " * (at your option) any later version.";
    stream << "\n";
    stream << indent_str;
    stream << " *";
    stream << "\n";
    stream << indent_str;
    stream << " * This program is distributed in the hope that it will be useful,";
    stream << "\n";
    stream << indent_str;
    stream << " * but WITHOUT ANY WARRANTY; without even the implied warranty of";
    stream << "\n";
    stream << indent_str;
    stream << " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the";
    stream << "\n";
    stream << indent_str;
    stream << " * GNU General Public License for more details.";
    stream << "\n";
    stream << indent_str;
    stream << " *";
    stream << "\n";
    stream << indent_str;
    stream << " * You should have received a copy of the GNU General Public License";
    stream << "\n";
    stream << indent_str;
    stream << " * along with this program; if not, write to the Free Software";
    stream << "\n";
    stream << indent_str;
    stream << " * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.";
    stream << "\n";
    stream << indent_str;
    stream << " *";
    stream << "\n";
    stream << indent_str;
    stream << " */";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "#include <iostream>";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "using std::cout;";
    stream << "\n";
    stream << indent_str;
    stream << "using std::endl;";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "#define MYVAR ";
    stream << myvar;
    stream << "\n";
    stream << indent_str;
    stream << "#define ";
    stream << mydef;
    stream << " ";
    stream << myvar;
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "extern int yyparse() ;";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "int";
    stream << "\n";
    stream << indent_str;
    stream << "main()";
    stream << "\n";
    stream << indent_str;
    stream << "{";
    stream << "\n";
    stream << indent_str;
    stream << "  cout << \"";
    stream << mydef;
    stream << " is \" << ";
    stream << mydef;
    stream << " << endl;";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "  cout << \"while MYVAR is defined as \" << ";
    stream << myvar;
    stream << " << endl;";
    stream << "\n";
    stream << indent_str;
    stream << "\n";
    stream << indent_str;
    stream << "  return 0;";
    stream << "\n";
    stream << indent_str;
    stream << "}";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // TEST_VARS_GEN_CLASS_H
