/*
 * File automatically generated by
 * gengen 1.4.3 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef CALLEXTFUN_LUA_GEN_CLASS_H
#define CALLEXTFUN_LUA_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class callextfun_lua_gen_class
{
 protected:
  string name;

 public:
  callextfun_lua_gen_class()
  {
  }
  
  callextfun_lua_gen_class(const string &_name) :
    name (_name)
  {
  }

  void set_name(const string &_name)
  {
    name = _name;
  }

  void generate_callextfun_lua(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "\n";
    stream << indent_str;
    stream << "if(record.";
    stream << name;
    stream << ") then";
    stream << "\n";
    stream << indent_str;
    stream << "  generate_string(record.";
    stream << name;
    stream << ", stream, indent + string.len(indent_str))";
    stream << "\n";
    stream << indent_str;
    stream << "else";
    stream << "\n";
    stream << indent_str;
    stream << "  generate_";
    stream << name;
    stream << "(stream, record, indent + string.len(indent_str))";
    stream << "\n";
    stream << indent_str;
    stream << "end";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // CALLEXTFUN_LUA_GEN_CLASS_H
