/*
 * File automatically generated by
 * gengen 1.0 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef EXTERN_FUNCTION_GEN_CLASS_H
#define EXTERN_FUNCTION_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class extern_function_gen_class
{
 protected:
  string name;
  string structname;

 public:
  extern_function_gen_class()
  {
  }
  
  extern_function_gen_class(const string &_name, const string &_structname) :
    name (_name), structname (_structname)
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  void set_name(const string &_name)
  {
    name = _name;
  }

  void set_structname(const string &_structname)
  {
    structname = _structname;
  }

  void generate_extern_function(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "extern void generate_";
    generate_string (name, stream, indent + indent_str.length ());
    stream << "(FILE *stream, struct ";
    generate_string (structname, stream, indent + indent_str.length ());
    stream << " *record, unsigned int indent);";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // EXTERN_FUNCTION_GEN_CLASS_H
