/*
 * File automatically generated by
 * gengen 1.0 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef GENMETHOD_BODY_GEN_CLASS_H
#define GENMETHOD_BODY_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class genmethod_body_gen_class
{
 protected:
  string geninstructions;

 public:
  genmethod_body_gen_class()
  {
  }
  

  virtual ~genmethod_body_gen_class()
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  virtual void generate_geninstructions(ostream &stream, unsigned int indent) = 0;

  void set_geninstructions(const string &_geninstructions)
  {
    geninstructions = _geninstructions;
  }

  void generate_genmethod_body(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "{";
    stream << "\n";
    stream << indent_str;
    stream << "  string indent_str (indent, ' ');";
    stream << "\n";
    stream << indent_str;
    stream << "  indent = 0;";
    stream << "\n";
    stream << indent_str;
    indent = 2;
    if (geninstructions.size () > 0)
      generate_string (geninstructions, stream, indent + indent_str.length ());
    else
      generate_geninstructions (stream, indent + indent_str.length ());
    indent = 0;
    stream << indent_str;
    stream << "}";
  }
};

#endif // GENMETHOD_BODY_GEN_CLASS_H
