/*
 * File automatically generated by
 * gengen 1.0 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef GENMETHOD_GEN_CLASS_H
#define GENMETHOD_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class genmethod_gen_class
{
 protected:
  string genmethbody;
  string genname;
  string methend;

 public:
  genmethod_gen_class()
  {
  }
  
  genmethod_gen_class(const string &_genmethbody, const string &_genname, const string &_methend) :
    genmethbody (_genmethbody), genname (_genname), methend (_methend)
  {
  }

  virtual ~genmethod_gen_class()
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  virtual void generate_genmethbody(ostream &stream, unsigned int indent) = 0;

  void set_genmethbody(const string &_genmethbody)
  {
    genmethbody = _genmethbody;
  }

  void set_genname(const string &_genname)
  {
    genname = _genname;
  }

  void set_methend(const string &_methend)
  {
    methend = _methend;
  }

  void generate_genmethod(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "void generate_";
    generate_string (genname, stream, indent + indent_str.length ());
    stream << "(ostream &stream, unsigned int indent = 0)";
    generate_string (methend, stream, indent + indent_str.length ());
    stream << "\n";
    stream << indent_str;
    if (genmethbody.size () > 0)
      generate_string (genmethbody, stream, indent + indent_str.length ());
    else
      generate_genmethbody (stream, indent + indent_str.length ());
  }
};

#endif // GENMETHOD_GEN_CLASS_H
