/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef OUTPUTLUAVAR_GEN_CLASS_H
#define OUTPUTLUAVAR_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class outputluavar_gen_class
{
 protected:
  string name;

 public:
  outputluavar_gen_class()
  {
  }
  
  outputluavar_gen_class(const string &_name) :
    name (_name)
  {
  }

  static void
  generate_string(const string &s, ostream &stream, unsigned int indent)
  {
    if (!indent || s.find('\n') == string::npos)
      {
        stream << s;
        return;
      }

    string::size_type pos;
    string::size_type start = 0;
    string ind (indent, ' ');
    while ( (pos=s.find('\n', start)) != string::npos)
      {
        stream << s.substr (start, (pos+1)-start);
        start = pos+1;
        if (start+1 <= s.size ())
          stream << ind;
      }
    if (start+1 <= s.size ())
      stream << s.substr (start);
  }

  void set_name(const string &_name)
  {
    name = _name;
  }

  void generate_outputluavar(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << "(record.";
    generate_string (name, stream, indent + indent_str.length ());
    stream << ") and record.";
    generate_string (name, stream, indent + indent_str.length ());
    stream << " or \"\"";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // OUTPUTLUAVAR_GEN_CLASS_H
